WikiTitle = Chippewa Software
MainUrl = http://www.chipsofttech.com/site/
Theme = Default
ContactEmail = admin@chipsoftttech.com
SenderEmail = admin@chipsofttech.com
SmtpServer = smtp.server.com
SmtpUsername = 
SmtpPassword = 
SmtpPort = -1
SmtpSsl = NO
DefaultPage = MainPage
EnableDoubleClickEditing = NO
DisableBreadcrumbsTrail = YES
DateTimeFormat = ddd, dd MMM yyyy hh':'mm' 'tt
DefaultLanguage = en-US
DefaultTimezone = -300
UsersCanRegister = NO
AccountActivationMode = ADMIN
DisableCaptchaControl = NO
DiscussionPermissions = LOCKED
UsersCanCreateNewPages = YES
UsersCanCreateNewCategories = NO
UsersCanManagePageCategories = NO
UsersCanViewFiles = NO
UsersCanUploadFiles = NO
UsersCanDeleteFiles = NO
PrivateAccess = NO
PublicAccess = NO
FileManagementInPublicAccessAllowed = NO
DisableConcurrentEditing = NO
AllowedFileTypes = jpg|jpeg|gif|png|tif|tiff|bmp|htm|html|zip|rar|pdf|txt
ScriptTagsAllowed = NO
LoggingLevel = 3
MaxLogSize = 64
ConfigVisibleToAdmins = NO
DisableAutomaticVersionCheck = YES
MaxFileSize = 10240
DisableCache = NO
CacheSize = 100
CacheCutSize = 20
FileAccessTries = 10
FileAccessTryDelay = 50
EnableViewStateCompression = NO
EnableHttpCompression = NO
UsernameRegex = ^\w[\w\ !$@%^\.\(\)]{3,25}$
PasswordRegex = ^\w[\w~!@#$%^\(\)\[\]\{\}\.,=\-_\ ]{6,25}$
DisableKeepAlive = NO
MaxKeepAlive = 10
DefaultPagesProvider = ScrewTurn.Wiki.PagesStorageProvider
DefaultUsersProvider = ScrewTurn.Wiki.UsersStorageProvider
